import { NavItem } from "reactstrap";

export const projects = [
    {
        id:2,
        projecttitle:"Vegan Sometimes",
        projectrole:"Web Design, UI Design, Wordpress Theme Design",
        description:"Vegan Somtimes is a wordpress site built using Javascript, HTML, CSS, and PHP.  It enables users to find vegan recipes as they transition into, or continue their vegan lifestlyes.  The client was looking to fill a hole in the vegan recipe market.",
        projectimage:"/assets/images/vegansometimesscreenshot.png",
        onedescription:"A wordpress site that enables users to search vegan recipes",
        projectprompt:"Design and deploy a website that makes it easy to find vegan recipes",
        problem:"There is no place on the internet that makes it easy to find vegan recipes without ill-placed advertisements and pop-ups",
        goal:"Design a website with a clean interface that makes it easy to find vegan recipes by meal-type or to search vegan recipes by title",
        myrole:"Programmer, Website Designer, UI Designer, Wordpress Theme Designer",
        painpointstitle1:"Pop-Up Advertisements",
        painpointstitle2:"Non-vegan recipes",
        painpointstitle3:"Non-categorized recipes",
        painpointscontent1:"Most recipe websites have too many advertisements and pop-up advertisements that take away from the user experience and make the site difficult to navigate",
        painpointscontent2:"There are no recipe sites that focus solely on vegan recipes.  Most websites have a vegamn recipe section, but no website focused only on vegan recipes",
        painpointscontent3:"A lot recipe sites lack categories for recipe types.  This site solves that problem by breaking down recipes into categories",
        figmalink:"https://www.figma.com/file/eTidxXQBdXbvKx55toaSOa/VeganRecipe.com?node-id=0%3A1",
        sitescreenshot1:"/assets/images/vegansometimesscreenshot1.png",
        sitescreenshot2:"/assets/images/vegansometimesscreenshot2.png",
        sitescreenshot3:"/assets/images/vegansometimesscreenshot3.png",
        websitelink:"https://vegan-sometimes.com/",
        githublink:"https://github.com/mrcmyk12/vegan-sometimes",
        impact:"This website is a go-to place for vegan recipes online.  It takes the hassle out finding vegan recipes to incorporate into your already existing vegan diet.  It also makes it easy to begin the transition to a vegan diet.",
        learned:"I learned the steps it takes to create and deploy a wordpress website. I increased my PHP skills as well as improved my skills with SQL Databases.",
        steptitle1:"User Created Content",
        steptitle2:"User Comments",
        steptitle3:"User Ratings",
        step1:"Create a way for users to submit their very own vegan recipes to increase recipes on the site",
        step2:"Create a way for users to add their own comments to the site to critique or give tips on a particular recipe",
        step3:"Create a user rating systems for all recipes"
    },
	{
		id: 0,
		projecttitle: "Movie Ticket Reservation App",
		projectrole: "UX Design, Research, User Interface Design",
		description:
			"This movie ticketing app presents a streamlined interface to purchase tickets from your local theater.  It provides a plot synopsis, and trailers for the movies playing at your local theaters.  It is meant for people who don’t want to wait in line to buy movie tickets or for people on the go (busy parents, single parents, busy professionals) who want to purchase tickets easily and affordably. ",
		projectimage: "/assets/images/FreeGuyTitleImage.png",
        onedescription:'A mobile app that makes it easy to reserve movie tickets on-the-go in as few steps as possible.',
        projectprompt:'Design an app that solves a problem in an existing industry',
        problem:'Users want to be able to reserve movie tickets in as little time as possible.',
        goal:'Design a mobile app that makes it easy to reserve movie tickets on the go in as few steps as possible.',
        myrole:'UX Designer, UI Designer designing app from conception to delivery',
        researchsummary:`I conducted interviews and created empathy maps to understand the users (for whom the app is designed for) and their needs.  A primary user group identified through research were working professionals and single parents who don't have a lot of time to spend on reserving movie tickets`,
        painpointstitle1:'Time',
        painpointstitle2:'Confusion',
        painpointstitle3:'Knowledge',
        painpointscontent1:"Theater-going adults don’t want to spend a lot of time picking out seats.  Or figuring out which seats give the best view",
        painpointscontent2:'Existing movie ticket reservation apps are cluttered and confusing',
        painpointscontent3:"Users don’t know what movies are playing.  Or know nothing about the movies that are playing (i.e plot, rating, critical reception)",
        persona:'Karen  is a working mom and wife who needs a quick and intuitive way to reserve movie theater tickets because her family enjoys watching films, but doesn’t have a lot of free time to reserve tickets and figure out how to use an app.  Below are the User Persona and the User Journey Map',
        personaimage:'/assets/images/MovieAppUserPersona.png',
        personauserjourneymap:'/assets/images/MovieAppUserJourneyMap.png',
        digitalwireframe1:'/assets/images/TicketAppLF1.png',
        digitalwireframe2:'assets/images/TicketAppLF2.png',
        digitalwireframe3:'assets/images/TicketAppLF3.png',
        digitalmockup1:'assets/images/TicketAppMU1.png',
        digitalmockup2:'assets/images/TicketAppMU2.png',
        digitalmockup3:'assets/images/TicketAppMU3.png',
        usabilityfinding1:'Users want order confirmation',
        usabilityfinding2:'Selecting a movie showtime is confusing',
        usabilityfinding3:'Users were unaware on what to do on some screens',
        lowfidelitylink:'https://www.figma.com/proto/irdj8U81k8AE32GGXPJ9V7/Movie-App-Wireframe?node-id=2%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=2%3A2&show-proto-sidebar=1',
        highfidelitylink:'https://www.figma.com/proto/irdj8U81k8AE32GGXPJ9V7/Movie-App-Wireframe?node-id=45%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=45%3A2&show-proto-sidebar=1',
        accessibilitycontent1:'Provided access to users who are vision impaired through adding alt text to images for screen readers.',
        accessibilitycontent2:'Used icons to help make navigation easier.',
        accessibilitycontent3:'Made digital ticket access able to be done with one hand for users who lack a second hand (amputation, crutch, cast)',
        impact:'This app makes reserving tickets online simple and intuitive.  It should increase movie theater patronage due to the fact that there is very little friction in ordering tickets on the app',
        learned:'While designing this app I learned the importance of iteration and outside perspective.  Through gathering information and iterating over and over again, I think I came away with a better and more fleshed out app which in the end provides a better user experience.',
        steptitle1:'Usability Study #2',
        steptitle2:'Mobile Ordering',
        steptitle3:'Theater Review',
        step1:'Conduct more user field studies to improve on the current app and to guide which features to introduce next.',
        step2:'A new feature I would like to implement is the ability to place orders for concessions ahead of arrival so that there is no waiting in line.',
        step3:'Another feature I would like to introduce are reviews of the theaters themselves in order to enable users to make more informed choices when choosing theaters.'     

	},
	{
		id: 1,
		projecttitle: "Local Business Finder",
		projectrole: "UX Design, Research, User Interface Design",
		description:
			"Local Business Finder is a mobile-responsive website that enables the user to find local businesses.  In addition there are features that allow the user to rate a specific business and leave comments.  The user experience is meant to create a sense of community around local businesses.",
		projectimage: "/assets/images/LocalBusinessFinderTitleImageMobile.png",
        onedescription: `An app that allows users to search local businesses and helps users determine the quality of businesses services`,
        projectprompt:'Design a responsive website that helps users solve an everyday problem',
        problem:'Users want to support local businesses but they have no way to know if it’s a quality business.',
        goal:'Design an app that allows users to search local businesses and helps users determine the quality of the business’s services.',
        myrole:'UX Designer, UI Designer from design to delivery.',
        researchsummary:'Through research and interviews I determined users wanted an easier way to find local businesses than the options offered by Yelp and other large search applications.  The target audience are users between 25 and 40',
        painpointstitle1:'Finding Local Businesses',
        painpointstitle2:'Rating Local Businesses',
        painpointstitle3:'Remembering Businesses Visited',
        painpointscontent1:'Finding local businesses from a source users trust.',
        painpointscontent2:'Letting people know about your favorite local business',
        painpointscontent3:'Recalling visits to local businesses',
        persona:'Claire  is a single millennial in a large metropolitan area  who needs ways to quickly find and research local businesses because she likes to support small businesses.  Below are the User Persona and User Journey Map',
        personaimage:'/assets/images/LocalBusinessFinderPersona.png',
        personauserjourneymap:'/assets/images/LocalBusinessFinderUserJourneyMap.png',
        digitalwireframe1:'/assets/images/LocalBusinessLF1.png',
        digitalwireframe2:'/assets/images/LocalBusinessLF2.png',
        digitalwireframe3:"/assets/images/LocalBusinessLF3.png",
        digitalmockup1:'/assets/images/LocalBusinessMU1.png',
        digitalmockup2:'/assets/images/LocalBusinessMU2.png',
        digitalmockup3:"/assets/images/LocalBusinessMU3.png" ,
        usabilityfinding1:'Users want feedback on local businesses',
        usabilityfinding2:'Users want to be able to share and log the businesses they went to',
        usabilityfinding3:'Users want a rating system they can trust',
        lowfidelitylink:'https://www.figma.com/proto/4qTBMTVgLRKEZXI1IHG0mG/Local-Business-Finder?node-id=22%3A468&scaling=scale-down&page-id=0%3A1&starting-point-node-id=22%3A468&show-proto-sidebar=1',
        highfidelitylink:'https://www.figma.com/proto/4qTBMTVgLRKEZXI1IHG0mG/Local-Business-Finder?node-id=136%3A402&scaling=scale-down&page-id=0%3A1&starting-point-node-id=136%3A402&show-proto-sidebar=1',
        accessibilitycontent1:'Included alt text for the visually impaired and screen readers.',
        accessibilitycontent2:'Described the handicap accessibility of each local business featured.',
        accessibilitycontent3:'Included icons wherever it was possible to make navigation easier.',
        impact:'This app gives local businesses a chance to shine and create a more cohesive community that supports small businesses.',
        learned:'While designing this app, I learned many things. However, I think the biggest takeaway was patience through iteration.  This app looked very different at several points in the iterative process.  But by sticking with the process I think the app came out better.',
        steptitle1:'Usabilty Study #2',
        steptitle2:'Ratings System',
        steptitle3:"Usability Follow-Up",
        step1:'Conduct another round of usability studies to see which features need to be added to the app.',
        step2:'Upgrade the ratings system to be more specific and indicate certain business attributes that users would find useful.',
        step3:'Conduct another round of usability studies to see if the issues from first usability study were addressed properly.'
	},
];

export function getProjects() {
    return projects;
}

export function getProject(id) {
    return projects.find(
        project => project.id === id
    )
}


